LightYear.JunFuTrans.WebSite/Controllers/CustomerShouldPayController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using ExcelDataReader;
using LightYear.JunFuTrans.BL.BE.Account;
using LightYear.JunFuTrans.BL.BE.Barcode;
using LightYear.JunFuTrans.BL.BE.CustomerShouldPay;
using LightYear.JunFuTrans.BL.Services.CustomerShouldPay;
using LightYear.JunFuTrans.DA.JunFuDb;
using LightYear.JunFuTrans.DA.JunFuTransDb;
using LightYear.JunFuTrans.DA.Repositories.CustomerShouldPay;
using LightYear.JunFuTrans.DA.Repositories.Station;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace LightYear.JunFuTrans.WebSite.Controllers
{
    public class CustomerShouldPayController : Controller
    {
        public ICustomerShouldPayService CustomerShouldPayService { get; set; }

        public IStationRepository StationRepository { get; set; }

        private readonly IConfiguration config;

        public CustomerShouldPayController(ICustomerShouldPayService customerShouldPayService, IStationRepository stationRepository, IConfiguration config)
        {
            CustomerShouldPayService = customerShouldPayService;
            StationRepository = stationRepository;
            this.config = config;
        }


        #region 客戶應收帳款
        public IActionResult Search()
        {
            var claim = HttpContext.User.Claims.First(c => c.Type == "UserInfo");
            var userInfoStr = claim.Value;
            UserInfoEntity userInfoEntity = JsonConvert.DeserializeObject<UserInfoEntity>(userInfoStr);
            string stationScode = userInfoEntity.Station;

            if (!stationScode.StartsWith("F"))
                ViewBag.Station = StationRepository.GetStationCodeByStationScode(stationScode);
            return View();
        }

        public IActionResult GetCustomerShouldPayEntity([FromQuery] string filter, string callback = "callback")
        {
            SearchFilter f = JsonConvert.DeserializeObject<SearchFilter>(filter);
            List<CustomerPaymentEntity> data = new List<CustomerPaymentEntity>();

            if (f.CustomerCode == "")
            {
                data = CustomerShouldPayService.GetByStationAndMonth(f.StationCode, f.Date.Year, f.Date.Month, f.IsPaid).ToList();
            }

            else
            {
                //CustomerShouldPayService.InitializeFreightByCustomers(f.CustomerCode, f.Date.Year, f.Date.Month);
                data.Add(CustomerShouldPayService.GetByCustomerAndMonth(f.CustomerCode, f.Date.Year, f.Date.Month));
            }

            string serializedEntity = JsonConvert.SerializeObject(data);
            string output = string.Format("{0}({1})", callback, serializedEntity);

            return Content(output);
        }

        public IActionResult UpdateAccountReceivable(string models, string stringDate, string callback = "callback")
        {
            IEnumerable<CustomerPaymentEntity> entity = JsonConvert.DeserializeObject<IEnumerable<CustomerPaymentEntity>>(models);
            CustomerPaymentEntity modified = entity.Last();

            // 抓回來是UTC，要再加8小時
            if (modified.PaidDate != null)
                modified.PaidDate = modified.PaidDate?.AddHours(8);

            DateTime date = DateTime.Parse(stringDate);
            modified.ShipDateStart = new DateTime(date.Year, date.Month, 1);
            modified.ShipDateEnd = new DateTime(date.Year, date.Month, DateTime.DaysInMonth(date.Year, date.Month));

            CustomerShouldPayService.UpdateAccountReceivable(modified);

            string output = string.Format("{0}({1})", callback, models);
            return Content(output);
        }

        public IActionResult ViewDetailByCustomer(string customerCode, int year, int month)
        {
            CustomerPaymentEntity data = CustomerShouldPayService.GetCustomerPaymentByCustomerAndMonth(customerCode, year, month);

            return View(data);
        }

        public async Task<IActionResult> Save([FromBody] SaveFreightAndTypeEntity entity)
        {
            //int pickUpType = (int)Enum.Parse(typeof(PickUpGoodTypeEntity), entity.PickUpType);
            JunFuWebServiceInService.WebServiceSoapClient webServiceSoapClient = new JunFuWebServiceInService.WebServiceSoapClient(JunFuWebServiceInService.WebServiceSoapClient.EndpointConfiguration.WebServiceSoap);
            //string response = await webServiceSoapClient.SaveFreightAndTypeAsync(entity.CheckNumber, entity.Freight, pickUpType.ToString());
            string[] checkNum = { entity.CheckNumber };
            int[] freight = { entity.Freight };
            string response = await webServiceSoapClient.SaveFreightBatchAsync(checkNum, freight);
            return Content(response);
        }

        public IActionResult GetFreightByCustomerAndType(string customerCode, string type)
        {
            CustomerShippingFee shippingFee = CustomerShouldPayService.GetShippingFeeByCustomerCodeOrDefault(customerCode);
            PickUpGoodTypeEntity pickUpType = (PickUpGoodTypeEntity)Enum.Parse(typeof(PickUpGoodTypeEntity), type);
            int fee = CustomerShouldPayService.GetFeeByCustomerShippingFeeEntity(pickUpType, shippingFee);

            string output = JsonConvert.SerializeObject(new { freight = fee });

            return Content(output);
        } 
        #endregion

        public IActionResult ShippingFeeEditor()
        {
            return View();
        }

        public IActionResult GetShippingFeeEntity(string filter, string callback = "callback")
        {
            var searchFilter = JsonConvert.DeserializeObject<SearchFilter>(filter);

            List<CustomerShippingFeeEntity> result;

            if(searchFilter.CustomerCode.Length > 0)
            {
                result = CustomerShouldPayService.GetShippingFeeByCustomerCode(searchFilter.CustomerCode);
            }
            else if(searchFilter.StationCode.Length > 0 && searchFilter.StationCode != "-1")
            {
                result = CustomerShouldPayService.GetShippingFeeByStation(searchFilter.StationCode);
            }
            else
            {
                result = CustomerShouldPayService.GetAllCustomerShippingFee();
            }

            if (result == null)
            {
                result = CustomerShouldPayService.GetShippingFeeByCustomerCode("0");
            }

            string output = string.Format("{0}({1})", callback, JsonConvert.SerializeObject(result));

            return Content(output);
        }

        public IActionResult UpdateShippingFee(string models, string callback = "callback")
        {
            List<CustomerShippingFeeEntity> entities = JsonConvert.DeserializeObject<List<CustomerShippingFeeEntity>>(models);

            var lastOne = entities.Last();
            var claim = HttpContext.User.Claims.First(c => c.Type == "UserInfo");
            var userInfoStr = claim.Value;
            UserInfoEntity userInfoEntity = JsonConvert.DeserializeObject<UserInfoEntity>(userInfoStr);
            string account = userInfoEntity.UserAccount;

            var returnEntity = CustomerShouldPayService.UpdateShippingFee(lastOne, account);

            string output = string.Format("{0}({1})", callback, JsonConvert.SerializeObject(returnEntity));

            return Content(output);
        }

        [HttpPost]
        public async Task<IActionResult> ImportFile(IFormFile file)
        {
            bool resultCode = true;
            string errorMessage = string.Format("沒有問題");

            try
            {
                List<AccountReceivable> Entities = new List<AccountReceivable>();
                string fullPath = string.Empty;

                if (file.Length > 0)
                {
                    var savePath = this.config.GetValue<string>("UploadFileUrl");
                    string uniqueFileName = CustomerShouldPayService.GetUniqueFileName(file.FileName);
                    fullPath = string.Format("{0}/{1}", savePath, uniqueFileName);
                    using (FileStream stream = new FileStream(fullPath, FileMode.Append))
                    {
                        await file.CopyToAsync(stream);
                    }

                    System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
                    using (var stream = System.IO.File.Open(fullPath, FileMode.Open, FileAccess.Read))
                    {
                        using (var reader = ExcelReaderFactory.CreateReader(stream))
                        {
                            var result = reader.AsDataSet();

                            var rows = result.Tables[0].Rows.Count;//獲取總行數

                            if (rows > 1) //除了標題行外有資料才讀取
                            {
                                for (int i = 1; i < rows; i++) // 避開標題行，從第二行開始讀取
                                {
                                    AccountReceivable Entity = new AccountReceivable(); // i每加1，就new一個Entity
                                    Entity.ElectronicReceipt = result.Tables[0].Rows[i][0].ToString();
                                    Entity.InvoiceId = result.Tables[0].Rows[i][11].ToString();
                                    Entities.Add(Entity);
                                }
                            }
                            else
                            {
                                return Content("沒有資料無法上傳");
                            }

                        }
                    }
                }

                CustomerShouldPayService.UpdateElectricReceipt(Entities);

                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }

                return View();
            }
            catch (Exception e)
            {

LightYear.JunFuTrans.WebSite/Views/CustomerShouldPay/ImportFile.cshtml
    <script>
    window.alert("上傳成功");
    location.href = '/CustomerShouldPay/Search';
    </script>

LightYear.JunFuTrans.WebSite/Views/CustomerShouldPay/Search.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAddMenu.cshtml";
}

<style>
</style>

<div class="demo-section k-content">
    <h3>客戶應收帳款</h3>

    <form style="margin-top: 2em;" id="form" method="post" enctype="multipart/form-data" asp-controller="CustomerShouldPay" asp-action="ImportFile">
        <input type="file" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" name="file" id="file" />
        <button class="k-button" id="upload">上傳電子發票檔</button>
    </form>

    <h4 style="margin-top: 2em;">結帳月份</h4>
    <input id="monthpicker" title="monthpicker" style="width: 100%" />

    <h4 style="margin-top: 2em;">發送站</h4>
    <input id="stations" value="" style="width: 100%" />

    <h4 style="margin-top: 2em;">客代</h4>
    <input id="customerCode" value="" style="width: 100%" />

    <h4 style="margin-top: 2em;">支付狀態</h4>
    <input id="isPaid" value="" style="width: 100%" />

    <button id="search">查詢</button>
    <button type="button" class="k-button" id="printGrid">列印</button>

    <button id="test" class="k-button">下載Excel</button>
</div>

<div id="grid"></div>
<div id="gridForExcel" style="visibility:hidden"></div>

<script>

    var customerCode = "";
    var stationCode = "@ViewBag.Station";

    $(document).ready(function () {

        $("#monthpicker").kendoDatePicker({
            start: "year",
            depth: "year",
            format: "MMMM yyyy",
            dateInput: true,
            culture: "zh-TW"
        });

        GenCustomerData();

        $("#stations").kendoDropDownList({
            filter: "startswith",
            dataTextField: "ShowName",
            dataValueField: "StationCode",
            value: "@ViewBag.Station",
            dataSource: {
                type: "odata",
                serverFiltering: true,
                transport: {
                    read: {
                        url: "/KendoSelect/GetStationFromTbStation?isNeedAllStation=false"
                    }
                }
            },
            select: function (e) {
                if ("@ViewBag.Station".length > 0) {
                    e.preventDefault();
                }
            },
            change: function (e) {
                var value = this.value();
                $("#customerCode").data("kendoDropDownList").value(-1);
                stationCode = value;
                GenCustomerData();
            }
        });

        var isPaidData = [
            {text: "全部", value: -1},
            {text: "已支付", value: 1},
            {text: "未支付", value: 0}
        ];

        $("#isPaid").kendoDropDownList({
            dataTextField: "text",
            dataValueField: "value",
            dataSource: isPaidData
        });
    });

    function GenCustomerData() {
        var getCustomerUrl = "/KendoSelect/GetCustomer?stationCode=" + stationCode;

        $("#customerCode").kendoDropDownList({
            filter: "startswith",
            dataTextField: "ShowName",
            dataValueField: "CustomerCode",
            dataSource: {
                type: "odata",
                serverFiltering: true,
                transport: {
                    read: {
                        url: getCustomerUrl
                    }
                }
            },
            change: function (e) {
                var value = this.value();
            }
        });
    }

    var dataSource = new kendo.data.DataSource({
        transport: {
            read: {
                url: "GetCustomerShouldPayEntity",
                dataType: "jsonp",
                data: function () {
                    return {
                        date: $("#monthpicker").data("kendoDatePicker").value(),
                        stationCode: $("#stations").data("kendoDropDownList").value(),
                        customerCode: $("#customerCode").data("kendoDropDownList").value(),
                        isPaid: $("#isPaid").data("kendoDropDownList").value()
                    }
                }
            },
            update: {
                url: "UpdateAccountReceivable",
                dataType: "jsonp"
            },
            parameterMap: function (data, type) {
                if (type == "read") {
                    return "filter=" + kendo.stringify(data);
                } else {
                    return {
                        models: kendo.stringify(data.models),
                        stringDate: kendo.toString($("#monthpicker").data("kendoDatePicker").value(), "yyyy-MM-dd")
                    };
                }
            }
        },
        batch: true,
        pageSize: 100,
        schema: {
            model: {
                id: "Id",
                fields: {
                    Id: { editable: false, nullable: true },
                    InvoiceId: { editable: false, type: "string" },
                    CustomerCode: { editable: false, type: "string" },
                    CustomerName: { editable: false, type: "string" },
                    TotalShouldPay: { editable: false, type: "number" },
                    Peices: { editable: false, type: "string" },
                    IsPaid: { type: "boolean" },
                    PaidDate: { type: "date", format: "{yyyy-MM-dd}" },
                    ElectricReceipt: { editable: false, type: "string", nullable: true }
                }
            }
        }
    });

    $("#search").kendoButton({
        click: function (e) {
            var filterData = {
                date: $("#monthpicker").data("kendoDatePicker").value(),
                stationCode: $("#stations").data("kendoDropDownList").value(),
                customerCode: $("#customerCode").data("kendoDropDownList").value(),
                isPaid: $("#isPaid").data("kendoDropDownList").value()
            };
            getData();

            // 視窗下拉到表格位置
            let gridOnePosition = $("#grid").offset().top;
            $("html, body").animate({ scrollTop: gridOnePosition }, 200);
        }
    });

    $('#printGrid').click(function () {
        printGrid();
    });


    function customBoolEditor(container, options) {
        $('<input class="k-checkbox" type="checkbox" name="IsPaid" data-type="boolean" data-bind="checked:IsPaid"><span> 已支付</span>').appendTo(container);
    }

    function showDetails(e) {
        e.preventDefault();

        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));

        var year = kendo.toString($("#monthpicker").data("kendoDatePicker").value().getFullYear());
        var month = kendo.toString($("#monthpicker").data("kendoDatePicker").value().getMonth() + 1);

        window.open("ViewDetailByCustomer?customerCode=" + dataItem.CustomerCode + "&year=" + year + "&month=" + month);
    }

    function getData() {
        if (!$("#grid").data("kendoGrid")) {
            $("#grid").kendoGrid({
                dataSource: dataSource,
                sortable: {
                    mode: "multiple",
                    allowUnsort: true
                },
                height: 500,
                columns: [
                    { field: "InvoiceId", title: "請款編號" },
                    { field: "CustomerCode", title: "客戶代號" },
                    { field: "CustomerName", title: "客戶名稱" },
                    { field: "TotalShouldPay", title: "應收帳款<br/>總金額" },
                    { field: "Peices", title: "總件數" },
                    { field: "IsPaid", title: "支付狀態", editor: customBoolEditor, template: '<span #= IsPaid ? "" : \'hidden="hidden"\' # >已支付</span>' },
                    { field: "PaidDate", title: "支付日期", template: '#= kendo.toString(PaidDate, "yyyy-MM/dd" ) #' },
                    { field: "ElectricReceipt", title: "電子發票" },
                    { command: { text: "帳款明細", click: showDetails, className: "detail" }, title: "&nbsp;", width: "100px" },
                    { command: ["edit"], title: "&nbsp;", width: "100px" }
                ],
                editable: "inline",
                dataBound: function (e) {
                    // 站所人員/當月不能編輯
                    if ("@ViewBag.Station".length > 0 ||
                        (new Date().getMonth() == $("#monthpicker").data("kendoDatePicker").value().getMonth()
                            && new Date().getFullYear() == $("#monthpicker").data("kendoDatePicker").value().getFullYear())) {
                        $(".k-grid-edit").addClass("k-state-disabled");
                    }
                }
            });
        }
        else {
            $("#grid").data("kendoGrid").dataSource.read();
        }
    }

    function printGrid() {
        var gridElement = $('#grid'),
            printableContent = '',
            win = window.open('', '', 'width=800, height=500'),
            doc = win.document.open();

        var htmlStart =
            '<!DOCTYPE html>' +
            '<html>' +
            '<head>' +
            '<meta charset="utf-8" />' +
            '<title>Kendo UI Grid</title>' +
            '<link href="https://kendo.cdn.telerik.com/' + kendo.version + '/styles/kendo.common.min.css" rel="stylesheet" /> ' +
            '<style>' +
            'html { font: 11pt sans-serif; }' +
            '.k-grid { border-top-width: 0; }' +
            '.k-grid, .k-grid-content { height: auto !important; }' +
            '.k-grid-content { overflow: visible !important; }' +
            '.k-grid .k-grid-header th { border-top: 1px solid; }' +
            '.k-grid-toolbar, .k-grid-pager > .k-link { display: none; }' +
            '</style>' +
            '</head>' +
            '<body>';

        var htmlEnd =
            '</body>' +
            '</html>';

        var gridHeader = gridElement.children('.k-grid-header');
        if (gridHeader[0]) {
            var thead = gridHeader.find('thead').clone().addClass('k-grid-header');
            printableContent = gridElement
                .clone()
                .children('.k-grid-header').remove()
                .end()
                .children('.k-grid-content')
                .find('table')
                .first()
                .children('tbody').before(thead)
                .end()
                .end()
                .end()
                .end()[0].outerHTML;
        } else {
            printableContent = gridElement.clone()[0].outerHTML;
        }

        doc.write(htmlStart + printableContent + htmlEnd);
        doc.close();
        win.print();
    }

    $("#test").click(function () {
        var options = {
            columns: [
                { field: "Year", title: "年度" },
                { field: "InvoiceId", title: "進銷單號碼" },
                { field: "Date", title: "日期" },
                { field: "Danbiye", title: "單別" },
                { field: "CustomerCodeForExcel", title: "客戶供應商" },
                { field: "CustomerCodeForExcel", title: "請款客戶" },
                { field: "No", title: "序號" },
                { field: "No", title: "產品代號" },
                { field: "Tax", title: "稅別" },
                { field: "ContainTax", title: "「單價含稅否」欄位" },
                { field: "PiecesForExcel", title: "數量" },
                { field: "TotalShouldPayWithoutTax", title: "未稅單價" },
                { field: "TotalShouldPayWithoutTax", title: "未稅金額" }
            ],
            columnMenu: {
                columns: true
            },
            dataSource: dataSource
        }
        options.columns.push({ field: "Empty", title: "製成品代號" });
        options.columns.push({ field: "Empty", title: "生產數量" });
        options.columns.push({ field: "Empty", title: "發票號碼" });
        options.columns.push({ field: "Empty", title: "發票日期" });
        options.columns.push({ field: "Empty", title: "傳票類別" });
        options.columns.push({ field: "Empty", title: "明細備註" });
        options.columns.push({ field: "Empty", title: "明細備註二" });
        options.columns.push({ field: "Empty", title: "主檔備註" });
        options.columns.push({ field: "Empty", title: "序號(客供商聯絡人)" });
        options.columns.push({ field: "Empty", title: "進銷特殊欄位" });
        options.columns.push({ field: "Empty", title: "序號(客戶供應商統編)" });
        options.columns.push({ field: "Empty", title: "序號(客戶供應商地址)" });
        options.columns.push({ field: "Empty", title: "包裝別" });
        options.columns.push({ field: "Empty", title: "外幣代號" });
        options.columns.push({ field: "Empty", title: "匯率" });
        options.columns.push({ field: "Empty", title: "外幣未稅單價" });
        options.columns.push({ field: "Empty", title: "外幣未稅金額" });
        options.columns.push({ field: "Empty", title: "訂單單號" });
        options.columns.push({ field: "Empty", title: "採購單號" });
        options.columns.push({ field: "Empty", title: "業務員代號" });
        options.columns.push({ field: "Empty", title: "部門\工地編號" });
        options.columns.push({ field: "Empty", title: "專案\項目編號" });
        $("#gridForExcel").kendoGrid(options);
        $("#gridForExcel").getKendoGrid().saveAsExcel();
    })
</script>

LightYear.JunFuTrans.WebSite/Views/CustomerShouldPay/ShippingFeeEditor.cshtml
@{
    ViewData["Title"] = "ShippingFeeEditor";
    Layout = "~/Views/Shared/_LayoutAddMenu.cshtml";
}

<div class="demo-section k-content">

    <h4>站所</h4>
    <input id="stations" value="" style="width: 100%" />

    <h4 style="padding-top:20px">出貨客代</h4>
    <input id="customers" value="" style="width: 100%" />

    <button id="search" class="offline-button">查詢</button>
    <a class="k-button" href="javascript:getExcel();">匯出Excel</a>

</div>

<div id="grid"></div>

<script>

    var stationCode = "";
    var dataSource;

    $(document).ready(function () {

        $("#stations").kendoDropDownList({
            filter: "startswith",
            dataTextField: "ShowName",
            dataValueField: "StationCode",
            value: "",
            dataSource: {
                type: "odata",
                serverFiltering: true,
                transport: {
                    read: {
                        url: "/KendoSelect/GetStation"
                    }
                }
            },
            change: function (e) {
                var value = this.value();
                $("#customers").data("kendoDropDownList").value(-1);
                stationCode = value;
                GenCustomerData();
            }
        });

        GenCustomerData();
    });

    function GenCustomerData() {
        var customers = $("#customers").kendoDropDownList({
            filter: "startswith",
            dataTextField: "ShowName",
            dataValueField: "CustomerCode",
            dataSource: {
                type: "odata",
                serverFiltering: true,
                transport: {
                    read: {
                        url: "/KendoSelect/GetCustomer?stationCode=" + stationCode,
                    }
                }
            }
        });
    }

    function getExcel() {

        var month = new Date().getMonth() + 1;

        var station = $("#stations").data("kendoDropDownList").text() + "_";

        var fileName = "零擔客戶運價表";

        if ($("#stations").data("kendoDropDownList").value() != "")
            fileName = month + "月_" + station + fileName
        else
            fileName = month + "月_" + fileName

        var grid = $("#grid").data("kendoGrid");
        grid.setOptions({
            excel: {
                allPages: true,
                fileName: fileName
            }
        });
        grid.saveAsExcel();
    }

    function rereadData() {
        dataSource = new kendo.data.DataSource({
            transport: {
                read: {
                    url: "GetShippingFeeEntity",
                    dataType: "jsonp",
                    cache: false,
                    data: function () {
                        return {
                            StationCode: $("#stations").data("kendoDropDownList").value(),
                            CustomerCode: $("#customers").data("kendoDropDownList").value()
                        };
                    }
                },
                update: {
                    url: "UpdateShippingFee",
                    dataType: "jsonp"
                },
                parameterMap: function (options, type) {
                    if (type == "read")
                        return { filter: kendo.stringify(options) };
                    else if (options.models) {
                        return { models: kendo.stringify(options.models) };
                    }
                }
            },
            batch: true,
            pageSize: 100,
            schema: {
                model: {
                    id: "Id",
                    fields: {
                        // Id: { editable:false, nullable: true },
                        StationName: { type: "string", editable: false },
                        CustomerCode: { type: "string", editable: false },
                        CustomerName: { type: "string", editable: false },
                        NoOne: { type: "number" },
                        NoTwo: { type: "number" },
                        NoThree: { type: "number" },
                        NoFour: { type: "number" },
                        S60: { type: "number" },
                        S90: { type: "number" },
                        S110: { type: "number" },
                        S120: { type: "number" },
                        S150: { type: "number" },
                        S180: { type: "number" },
                        HolidayPrice: { type: "number" },
                        PieceRate: { type: "number" },
                        LianYun: { type: "number" },
                        EffectiveDate: { type: "date" },
                    }
                }
            }
        });
    }
    
    $("#search").kendoButton({
        click: function (e) {
            rereadData();

            if ($("#grid").data("kendoGrid")) {                
                $("#grid").data("kendoGrid").dataSource.read();
            }

            $("#grid").html('').kendoGrid({
                dataSource: dataSource,
                sortable: {
                    mode: "multiple",
                    allowUnsort: true
                },
                height: 500,
                columns: [
                    { field: "StationName", title: "站所"},
                    { field: "CustomerCode", title: "客戶代號" },
                    { field: "CustomerName", title: "客戶名稱" },
                    { field: "NoOne", title: "1號袋", width: "50px" },
                    { field: "NoTwo", title: "2號袋", width: "50px" },
                    { field: "NoThree", title: "3號袋", width: "50px" },
                    { field: "NoFour", title: "4號袋", width: "50px" },
                    { field: "S60", title: "S60", width: "50px" },
                    { field: "S90", title: "S90", width: "50px"},
                    { field: "S110", title: "S110", width: "50px" },
                    { field: "S120", title: "S120", width: "50px"},
                    { field: "S150", title: "S150", width: "50px", width: "50px"},
                    { field: "HolidayPrice", title: "假日加價", width: "70px"},
                    { field: "PieceRate", title: "續件", width: "50px" },
                    { field: "LianYun", title: "聯運", width: "50px" },
                    { field: "EffectiveDate", title: "生效日期", format: "{0:yyyy/MM/dd}" },
                    {
                        command: [{ name: "edit", text: { edit: "編輯", update: "儲存", cancel: "取消" } }], title: "修改", width: "100px"
                    }],
                editable: "popup",
                dataBinding: function (e) {
                    dataSource = new kendo.data.DataSource({
                        data: []
                    });
                }
            });
           
            // 視窗下拉到表格位置
            let gridOnePosition = $("#grid").offset().top;
            $("html, body").animate({ scrollTop: gridOnePosition }, 200);
        }
    });
</script>