LightYear.JunFuTrans.WebSite/Controllers/TruckVendorPaymentAndMaintenanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using LightYear.JunFuTrans.BL.Services.TruckVendorPaymentAndMaintenance;
using LightYear.JunFuTrans.DA.JunFuTransDb;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IO;
using LightYear.JunFuTrans.BL.Services.GuoYangExportAndImport;
using ExcelDataReader;
using LightYear.JunFuTrans.BL.BE.Account;
using LightYear.JunFuTrans.DA.JunFuDb;
using LightYear.JunFuTrans.BL.BE.TruckVendorPaymentAndMaintenance;
using System.Globalization;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using LightYear.JunFuTrans.DA.Repositories.TruckVendorPaymentAndMaintenance;
using JunFuTrans.DA.JunFuTrans.DA;
using JunFuTrans.DA.JunFuTrans.condition;
using System.Text.RegularExpressions;

namespace LightYear.JunFuTrans.WebSite.Controllers
{
    public class TruckVendorPaymentAndMaintenanceController : Controller
    {
        ITruckVendorPaymentService TruckVendorPaymentService { get; set; }
        private readonly IConfiguration config;
        IGuoYangExportAndImportService GuoYangExportAndImportService { get; set; }

        public ITbItemCodesRepository TbItemCodesRepository { get; private set; }

        public ITruckVendorMaintenanceRepository TruckVendorMaintenanceRepository { get; set; }

        public ITruckVendorPaymentRepository TruckVendorPaymentRepository { get; set; }

        public IMapper Mapper { get; set; }


        public TruckVendorPaymentAndMaintenanceController(ITruckVendorPaymentService truckVendorPaymentService, IConfiguration config,
            IGuoYangExportAndImportService guoYangExportAndImportService, IMapper mapper, ITbItemCodesRepository itemCodesRepository,
            ITruckVendorMaintenanceRepository truckVendorMaintenanceRepository, ITruckVendorPaymentRepository truckVendorPaymentRepository)
        {
            TruckVendorPaymentService = truckVendorPaymentService;
            this.config = config;
            GuoYangExportAndImportService = guoYangExportAndImportService;
            Mapper = mapper;
            TbItemCodesRepository = itemCodesRepository;
            TruckVendorMaintenanceRepository = truckVendorMaintenanceRepository;
            TruckVendorPaymentRepository = truckVendorPaymentRepository;
        }
        public IActionResult Index()
        {
            var claim = HttpContext.User.Claims.First(c => c.Type == "UserInfo");

            var userInfoStr = claim.Value;

            UserInfoEntity userInfoEntity = JsonConvert.DeserializeObject<UserInfoEntity>(userInfoStr);

            ViewBag.UserAccount = userInfoEntity.UserAccount;

            //string truckVendorId = TruckVendorPaymentService.GetTruckVendorByTruckVendorAccountCode(userInfoEntity.UserAccount)?.Id.ToString();
            string truckVendorId = string.Empty;
            if (userInfoEntity.SupplierId != null)
            {
                var supplier = TruckVendorPaymentService.GetSupplierById((int)userInfoEntity.SupplierId);
                if (supplier != null)
                {
                    truckVendorId = supplier.supplier_id.ToString();
                }
            }
            ViewBag.TruckVendorId = truckVendorId ?? "";

            return View();
        }
        /// <summary>
        /// 維持舊版
        /// </summary>
        /// <returns></returns>
        public IActionResult Index_Old()
        {
            var claim = HttpContext.User.Claims.First(c => c.Type == "UserInfo");

            var userInfoStr = claim.Value;

            UserInfoEntity userInfoEntity = JsonConvert.DeserializeObject<UserInfoEntity>(userInfoStr);

            ViewBag.UserAccount = userInfoEntity.UserAccount;

            string truckVendorId = TruckVendorPaymentService.GetTruckVendorByTruckVendorAccountCode(userInfoEntity.UserAccount)?.Id.ToString();

            ViewBag.TruckVendorId = truckVendorId ?? "";

            return View();
        }
        public IActionResult GetSuppliersAccountCode()
        {
            return Json(TruckVendorPaymentService.GetSuppliersAccount().Select(a => a.AccountCode).ToList());
        }

        public IActionResult Upload()
        {
            var claim = HttpContext.User.Claims.First(c => c.Type == "UserInfo");

            var userInfoStr = claim.Value;

            UserInfoEntity userInfoEntity = JsonConvert.DeserializeObject<UserInfoEntity>(userInfoStr);

            if (isSupplierAccount(userInfoEntity))
            {
                TempData["Message"] = "本帳號權限無法進入此頁面。";
                return RedirectToAction("ErrorPage");
            }
            return View();
        }

        public IActionResult GetAllByMonthAndTruckVendor(DateTime month, string vendor, string callback = "callback")
        {
            DateTime start = new DateTime(month.Year, month.Month, 01, 00, 00, 00);

            DateTime end = start.AddMonths(1);

            var Entities = TruckVendorPaymentService.GetAllByMonthAndTruckVendor(start, end, vendor);

            string data = JsonConvert.SerializeObject(Entities);

            string output = string.Format("{0}({1})", callback, data);

            return Content(output);
        }

        public IActionResult GetAllByMonthAndTruckVendor_Old(DateTime month, string vendor, string callback = "callback")
        {
            DateTime start = new DateTime(month.Year, month.Month, 01, 00, 00, 00);

            DateTime end = start.AddMonths(1);

            var Entities = TruckVendorPaymentService.GetAllByMonthAndTruckVendor_Old(start, end, vendor);

            string data = JsonConvert.SerializeObject(Entities);

            string output = string.Format("{0}({1})", callback, data);

            return Content(output);
        }

        public IActionResult GetDisbursement(DateTime month, string vendor, string callback = "callback")
        {
            DateTime start = new DateTime(month.Year, month.Month, 01, 00, 00, 00);

            DateTime end = start.AddMonths(1);

            var Entities = TruckVendorPaymentService.GetDisbursementByMonthAndTruckVendor(start, end, vendor);

            string data = JsonConvert.SerializeObject(Entities);

            string output = string.Format("{0}({1})", callback, data);

            return Content(output);
        }
        public IActionResult GetDisbursement_Old(DateTime month, string vendor, string callback = "callback")
        {
            DateTime start = new DateTime(month.Year, month.Month, 01, 00, 00, 00);

            DateTime end = start.AddMonths(1);

            var Entities = TruckVendorPaymentService.GetDisbursementByMonthAndTruckVendor_Old(start, end, vendor);

            string data = JsonConvert.SerializeObject(Entities);

            string output = string.Format("{0}({1})", callback, data);

            return Content(output);
        }
        public IActionResult Save(string models, string callback = "callback")
        {
            List<TruckVendorPaymentLog> truckVendorPaymentLog = JsonConvert.DeserializeObject<List<TruckVendorPaymentLog>>(models);

            var claim = HttpContext.User.Claims.First(c => c.Type == "UserInfo");

            var userInfoStr = claim.Value;

            UserInfoEntity userInfoEntity = JsonConvert.DeserializeObject<UserInfoEntity>(userInfoStr);

            for (int i = 0; i < truckVendorPaymentLog.Count; i++)
            {
                if (truckVendorPaymentLog[i].Id == 0)
                {
                    truckVendorPaymentLog[i].CreateUser = userInfoEntity.UserAccount;
                }
                else
                {
                    truckVendorPaymentLog[i].UpdateUser = userInfoEntity.UserAccount;
                }
            }

            var ids = TruckVendorPaymentService.Save(truckVendorPaymentLog);

            for (int i = 0; i < ids.Count; i++)
            {
                truckVendorPaymentLog[i].Id = ids[i];
                truckVendorPaymentLog[i].VendorName = TruckVendorPaymentService.GetTruckVendors().Where(a => a.Id.ToString().Equals(truckVendorPaymentLog[i].VendorName)).FirstOrDefault()?.VendorName;
                truckVendorPaymentLog[i].Company = TruckVendorPaymentService.GetCompanies().Where(a => a.Id.ToString().Equals(truckVendorPaymentLog[i].Company)).FirstOrDefault()?.Name;
                truckVendorPaymentLog[i].FeeType = TruckVendorPaymentService.GetFeeTypes().Where(a => a.Id.ToString().Equals(truckVendorPaymentLog[i].FeeType)).FirstOrDefault()?.Name;
                truckVendorPaymentLog[i].RegisteredDate = truckVendorPaymentLog[i].RegisteredDate.Value.AddHours(-8);
            }

            models = JsonConvert.SerializeObject(truckVendorPaymentLog);

            string output = string.Format("{0}({1})", callback, models);
            return Content(output);
        }

        public IActionResult Update(string models, string callback = "callback")
        {
            List<TruckVendorPaymentLog> truckVendorPaymentLog = JsonConvert.DeserializeObject<List<TruckVendorPaymentLog>>(models);

            var claim = HttpContext.User.Claims.First(c => c.Type == "UserInfo");

            var userInfoStr = claim.Value;

            UserInfoEntity userInfoEntity = JsonConvert.DeserializeObject<UserInfoEntity>(userInfoStr);

            truckVendorPaymentLog[0].UpdateUser = userInfoEntity.UserAccount;

            TruckVendorPaymentService.Update(truckVendorPaymentLog[0]);

            string output = string.Format("{0}({1})", callback, models);

            return Content(output);
        }

        public IActionResult GetAllTruckVendors()
        {
            //return Json(TruckVendorPaymentService.GetTruckVendors());
            return Json(TruckVendorPaymentService.GetSupplier());
        }

        public IActionResult GetAllTruckVendors_Old()
        {
            return Json(TruckVendorPaymentService.GetTruckVendors());
        }

        public IActionResult GetFeeTypes()

LightYear.JunFuTrans.WebSite/Views/TruckVendorPaymentAndMaintenance/ErrorPage.cshtml
@{
    ViewData["Title"] = "KendoTest";
    Layout = "~/Views/Shared/_LayoutAddJFMenu.cshtml";
}
<div id="container">
    <div class="demo-section k-content">
        <h4>無法進入頁面</h4>
        <label style="color:red">
            @Html.Raw(ViewBag.msg)
        </label>
    </div>
</div>

LightYear.JunFuTrans.WebSite/Views/TruckVendorPaymentAndMaintenance/Upload.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAddJFMenu.cshtml";
}

<div class="demo-section k-content">
    <div>
        <h2>供應商收支明細整批匯入</h2><br />
        <form asp-controller="TruckVendorPaymentAndMaintenance" asp-action="Upload" method="post">
            <button asp-action="ExportFileByUrl" type="submit" name="exportexcel" class="btn btn-success">
                <i class="fa fa-download"></i>
                下載空白供應商明細檔案
            </button>
            <h6>最新版本為2023年4月10日</h6>
            <button asp-action="ExportBasicInformation" type="submit" name="exportBasicInfoExcel" class="btn btn-info">
                <i class="fa fa-download"></i>
                下載基本資料對照表
            </button>
        </form>
    </div><br />
    <form id="form" method="post" enctype="multipart/form-data" asp-controller="TruckVendorPaymentAndMaintenance" asp-action="ImportFile">
        <input type="file" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" name="file" id="file" />
        <button id="submit" class="btn btn-warning" UseSubmitBehavior="false">
            <i class="fa fa-upload"></i>上傳
        </button>
        <button id="submit2temp" class="btn btn-warning" disabled="disabled" hidden="hidden">
            <i class="fa fa-upload"></i>上傳
        </button>
    </form><br />
    <p id="response2"></p>
    <hr />
    @*
    取消下方表格
    <div>
        <h2>已上傳明細</h2><br />
        <div id="grid"></div>
    </div>
    *@
</div>

<script>
    $('#submit').click(function () {
        var button = $(this);
        var button2 = $('#submit2temp');
        button.hide();
        button2.removeAttr('hidden');
        button2.show();
        button2.attr('disabled', 'disabled');
        setTimeout(function () {
            button.show();
            button2.hide();
        }, 30000);
        //disable後無法post 改用雙按紐
        //setTimeout(function () {
        //    button2.removeAttr('disabled');
        //}, 3000);

        //if (!$('#text').val()) {
        //    alert('field empty');
        //    button.removeAttr('disabled');
        //} else {
        //    $('#message').html('done');
        //    $('#text').val('');
        //}
    });

    $("#response2").text("@Html.Raw(@TempData["Response"])".replace(/。/g, "\n"));

        @*dataSource = new kendo.data.DataSource({
            transport: {
                read: {
                    url: '/TruckVendorPaymentAndMaintenance/GetLatestUploadData?ImportRandomCode=' + '@TempData["importRandomCode"]',
                    dataType: "jsonp"
                },
                create: {
                    url: "/TruckVendorPaymentAndMaintenance/Save",
                    type: "POST",
                    dataType: "jsonp"
                },
                parameterMap: function (options, operation) {
                    if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    }
                }
            },
            batch: true,
            pageSize: 20,
            schema: {
                model: {
                    id: "Id",
                    fields: {
                        rowNumber: { editable: false, nullable: false, defaultValue: 1 },
                        Id: { editable: false, nullable: false, defaultValue: 0},
                        RegisteredDate: { type: "date", validation: { required: true } },
                        FeeType: { validation: { required: true } },
                        VendorName: { validation: { required: true }, nullable: true },
                        CarLicense: { validation: { required: false }, nullable: true },
                        Payment: { validation: { required: true }, nullable: true },
                        Memo: { validation: { required: true }, nullable: true },
                        Company: { validation: { required: false }, nullable: true },
                        Department: { validation: { required: false }, nullable: true },
                    }
                }
            }
        });*@

    //function grid_saveChanges(e) {
    //    //var grid = $("#grid").data("kendoGrid");
    //    if (!confirm("請先確認必填的欄位全部填齊再按下確定。")) {
    //        e.preventDefault();
    //    }
    //}

     //$("#grid").kendoGrid({
     //   dataSource: dataSource,
     //   navigatable: true,
     //   dataBound: function (e) {
     //        var rows = this.items();
     //        $(rows).each(function () {
     //            var index = $(this).index() + 1;
     //            var rowLabel = $(this).find(".row-number");
     //            $(rowLabel).html(index);
     //            var totalRecords = dataSource.total();
     //            $('.k-grid-count').text("共" + totalRecords + "筆");
     //        });
     //   },
     //   pageable: true,
     //   height: 300,
     //   toolbar: [{ name: "create", text: "新增" }, { name: "save", text: "儲存" }, { name: "cancel", text: "清空" }, { name: "count", text: "" }],
     //   columns:
     //       [{ field: "rowNumber", title: "序號", template: "<span class='row-number'></span>" },
     //       { hidden: true, field: "Id", title: "序號", width: "80px" },
     //           {
     //               field: "RegisteredDate", title: "發生日期(必填)", format: "{0: yyyy/MM/dd}", editor: function (container, options) {
     //                   if (options.model.Id > 0) {
     //                       var input = $('<div data-bind="text:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   }else {
     //                       $('<input required name="' + options.field + '"/>')
     //                           .appendTo(container).kendoDatePicker();
     //                   }
     //               }
     //           },
     //           {
     //               field: "FeeType", title: "交易項目(必填)", editor: function (container, options) {
     //                   if (options.model.Id > 0) {
     //                       var input = $('<div data-bind="text:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   } else {
     //                       FeeTypeDropDownEditor(container, options);
     //                   }
     //               }, width: "200px"
     //           },
     //           {
     //               field: "VendorName", title: "供應商名稱(必填)", editor: function (container, options) {
     //                   if (options.model.Id > 0) {
     //                       var input = $('<div data-bind="text:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   } else {
     //                       VendorsDropDownEditor(container, options);
     //                   }
     //               }, width: "250px"
     //           },
     //           {
     //               field: "CarLicense", title: "車號", editor: function (container, options) {
     //                   if (options.model.Id > 0) {
     //                       var input = $('<div data-bind="text:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   } else {
     //                       var input = $('<input data-bind="value:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   }
     //               }
     //           },
     //           {
     //               field: "Payment", title: "金額(必填)", editor: function (container, options) {
     //                   if (options.model.Id > 0) {
     //                       var input = $('<div data-bind="text:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   } else {
     //                       var input = $('<input required data-bind="value:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   }
     //               }
     //           },
     //           {
     //               field: "Memo", title: "摘要(必填)", editor: function (container, options) {
     //                   if (options.model.Id > 0) {
     //                       var input = $('<div data-bind="text:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   } else {
     //                       var input = $('<input required data-bind="value:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   }
     //               }
     //           },
     //           {
     //               field: "Department", title: "部門", editor: function (container, options) {
     //                   if (options.model.Id > 0) {
     //                       var input = $('<div data-bind="text:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   } else {
     //                       CompaniesDropDownEditor(container, options);
     //                   }
     //               }, width: "100px"
     //           },
     //           {
     //               field: "Company", title: "公司別", editor: function (container, options) {
     //                   if (options.model.Id > 0) {
     //                       var input = $('<div data-bind="text:' + options.field + '"/>');
     //                       input.appendTo(container);
     //                   } else {
     //                       CompaniesDropDownEditor(container, options);
     //                   }
     //               }, width: "100px"
     //           }
     //       ],
     //   editable: true,
     //});

    //var grid = $("#grid").data("kendoGrid");
    //grid.bind("saveChanges", grid_saveChanges);

    //function FeeTypeDropDownEditor(container, options) {
    //    $('<input required name="' + options.field + '"/>') // required
    //            .appendTo(container)
    //            .kendoDropDownList({
    //                autoBind: false,
    //                filter: "contains",
    //                dataTextField: "name",
    //                dataValueField: "name",
    //                dataSource: {
    //                    type: "jsonp",
    //                    transport: {
    //                        read: "/TruckVendorPaymentAndMaintenance/GetFeeTypes"
    //                    }
    //                }
    //            });
    //    }

    //    function CompaniesDropDownEditor(container, options) {
    //        $('<input name="' + options.field + '"/>') // not required
    //            .appendTo(container)
    //            .kendoDropDownList({
    //                autoBind: false,
    //                valuePrimitive: true,
    //                filter: "contains",
    //                dataTextField: "name",
    //                dataValueField: "name",
    //                dataSource: {
    //                    type: "jsonp",
    //                    transport: {
    //                        read: "/TruckVendorPaymentAndMaintenance/GetCompanies"
    //                    }
    //                }
    //            });
    //    }

    //    function VendorsDropDownEditor(container, options) {
    //        $('<input required name="' + options.field + '"/>')
    //            .appendTo(container)
    //            .kendoDropDownList({
    //                autoBind: false,
    //                filter: "contains",
    //                valuePrimitive: true,
    //                dataTextField: "vendorName",
    //                dataValueField: "vendorName",
    //                dataSource: {
    //                    type: "jsonp",
    //                    transport: {
    //                        read: "/TruckVendorPaymentAndMaintenance/GetAllTruckVendors"
    //                    }
    //                }
    //            });
    //    }
</script>

<style>
    .demo-section:not(.wide) {
        max-width: 1200px;
    }

    p {
        white-space: pre-wrap;
    }
</style>